apiVersion: v2
name: nudgebee-agent
description: Nudgebee Helm chart for Kubernetes
type: application
icon: https://nudgebee-documents.s3.amazonaws.com/images/Nudgebee-logo.png
# these are set to the right value by .github/workflows/release.yaml
# we use 0.0.1 as a placeholder for the version` because Helm wont allow `0.0.0` and we want to be able to run
# `helm install` on development checkouts without updating this file. the version doesn't matter in that case anyway
version: 0.0.97
appVersion: 0.0.97
dependencies:
- name: opencost
  version: 2.0.1
  condition: opencost.enabled
  repository: "https://opencost.github.io/opencost-helm-chart"
- name: clickhouse
  version: 23.3.1-debian-11-r0
  repository: registry.dev.nudgebee.pollux.in
  condition: opentelemetry-collector.enabled
- name: opentelemetry-collector
  version: 0.52.*
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  condition: opentelemetry-collector.enabled
