apiVersion: v2
name: nudgebee-agent
description: Nudgebee Helm chart for Kubernetes
type: application
icon: https://nudgebee-documents.s3.amazonaws.com/images/Nudgebee-logo.png
# these are set to the right value by .github/workflows/release.yaml
# we use 0.0.1 as a placeholder for the version` because Helm wont allow `0.0.0` and we want to be able to run
# `helm install` on development checkouts without updating this file. the version doesn't matter in that case anyway
version: 0.0.56
appVersion: 0.0.56
dependencies:
- name: opencost
  version: 1.28.0
  condition: opencost.enabled
  repository: "https://opencost.github.io/opencost-helm-chart"
- name: clickhouse
  version: 3.1.*
  repository: https://charts.bitnami.com/bitnami
  condition: opentelemetry-collector.enabled
- name: opentelemetry-collector
  version: 0.52.*
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  condition: opentelemetry-collector.enabled
