{{- if .Values.rsa }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nudgebee-agent.fullname" . }}-auth-config-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nudgebee-agent.labels" . | nindent 4 }}
    component: auth-config
type: Opaque
data:
{{- if and .Values.rsa.public .Values.rsa.private }}
  prv: {{ .Values.rsa.private }}
  pub: {{ .Values.rsa.public }}
{{- else }}
  prv: {{ .Values.rsa.prv | b64enc }}
  pub: {{ .Values.rsa.pub | b64enc }}
{{- end }}
{{- end }}
