kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "nudgebee-agent.fullname" . }}-forwarder-cluster-role
  namespace : {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - daemonsets
      - deployments
      - events
      - namespaces
      - nodes
      - persistentvolumes
      - pods
      - replicasets
      - replicationcontrollers
      #- secrets
      - services
      - serviceaccounts
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - "autoscaling"
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - "events.k8s.io"
    resources:
      - events
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - deployments/scale
      - replicasets
      - replicasets/scale
      - statefulsets
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - deployments/scale
      - ingresses
      - replicasets
      - replicasets/scale
      - replicationcontrollers/scale
    verbs:
      - get
      - list
      - watch
    
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list

{{- if .Values.openshift.enabled }}
  - apiGroups:
    - security.openshift.io
    resources:
    - securitycontextconstraints
    verbs:
    - use
    resourceNames:
    - {{ if .Values.openshift.createScc }}"{{ include "nudgebee-agent.fullname" . }}-scc"{{ else }}{{ .Values.openshift.sccName | quote }}{{ end }}
{{- end }}

{{- if (.Capabilities.APIVersions.Has "argoproj.io/v1alpha1/Rollout") }}
  - apiGroups:
    - argoproj.io
    resources:
    - rollouts
    verbs:
    - get
    - list
    - watch
{{- end }}

{{- if (.Capabilities.APIVersions.Has "karpenter.sh/v1beta1/NodePool") }}
  - apiGroups: 
    - karpenter.sh
    resources: 
    - nodepools
    - nodepools/status
    - nodeclaims
    - nodeclaims/status
    verbs: 
    - get 
    - list
    - watch
    - create
    - delete
    - patch
{{- end }}

{{- if (.Capabilities.APIVersions.Has "karpenter.k8s.aws/v1beta1/EC2NodeClass") }}
  - apiGroups: 
    - karpenter.k8s.aws
    resources: 
    - ec2nodeclasses
    verbs: 
    - get 
    - list
    - watch
    - create
    - delete
    - update
    - patch
{{- end }}

{{- if (.Capabilities.APIVersions.Has "karpenter.azure.com/v1alpha2/AKSNodeClass") }}
  - apiGroups: 
    - karpenter.azure.com
    resources: 
    - aksnodeclasses
    verbs: 
    - get 
    - list
    - watch
    - create
    - delete
    - update
    - patch
{{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nudgebee-agent.fullname" . }}-forwarder-service-account
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nudgebee-agent.fullname" . }}-forwarder-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "nudgebee-agent.fullname" . }}-forwarder-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "nudgebee-agent.fullname" . }}-forwarder-service-account
    namespace: {{ .Release.Namespace }}
