apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nudgebee-agent.fullname" . }}-forwarder
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nudgebee-agent.labels" . | nindent 4 }}
    component: forwarder
spec:
  selector:
    matchLabels:
      app: {{ include "nudgebee-agent.fullname" . }}-forwarder
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/kubewatch-configmap.yaml") . | sha256sum }}
        {{- if .Values.kubewatch.annotations }} {{ toYaml .Values.kubewatch.annotations | nindent 8 }}
        {{- end }}
        {{- if .Values.globalConfig.custom_annotations }} {{ toYaml .Values.globalConfig.custom_annotations | nindent 8 }}
        {{- end }}
      labels:
        {{- include "nudgebee-agent.labels" . | nindent 8 }}
        app: {{ include "nudgebee-agent.fullname" . }}-forwarder
        component: forwarder
    spec:
      serviceAccountName: {{ include "nudgebee-agent.fullname" . }}-forwarder-service-account
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      {{- if .Values.kubewatch.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml .Values.kubewatch.imagePullSecrets | nindent 6 }}
      {{- end }}
      containers:
      - name: kubewatch
        # this is a custom version of kubewatch built from https://github.com/aantn/kubewatch
        image: {{ .Values.kubewatch.image.repository }}:{{ .Values.kubewatch.image.tag | default "latest" }}
        imagePullPolicy: {{ .Values.kubewatch.imagePullPolicy }}
        env:
          - name: KW_CONFIG
            value: /config
          - name: ENABLE_PPROF
            value: {{ .Values.kubewatch.pprof | quote }}
          {{- if .Values.kubewatch.additional_env_vars }}
          {{ toYaml .Values.kubewatch.additional_env_vars | nindent 10 }}
          {{- end }}
        volumeMounts:
          - name: kubewatch-config
            mountPath: /config
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsUser: 1000    
        resources:
          requests:
            cpu: {{ .Values.kubewatch.resources.requests.cpu }}
            memory: {{ if .Values.isSmallCluster }}"64Mi"{{ else }}{{ .Values.kubewatch.resources.requests.memory | quote }}{{ end }}
          limits:
            memory: {{ if .Values.isSmallCluster }}"64Mi"{{ else }}{{ .Values.kubewatch.resources.requests.memory | quote }}{{ end }}
            {{ if .Values.kubewatch.resources.limits.cpu }}cpu: {{ .Values.kubewatch.resources.limits.cpu | quote }}{{ end }}
      volumes:
        - name: kubewatch-config
          configMap:
            name: {{ include "nudgebee-agent.fullname" . }}-kubewatch-config
      {{- if .Values.kubewatch.nodeSelector }}
      nodeSelector: {{ toYaml .Values.kubewatch.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.kubewatch.affinity }}
      affinity: {{ toYaml .Values.kubewatch.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.kubewatch.tolerations }}
      tolerations:  {{ toYaml .Values.kubewatch.tolerations | nindent 8 }}
      {{- end }}
