apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nudgebee-agent.fullname" . }}-kubewatch-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nudgebee-agent.labels" . | nindent 4 }}
    component: kubewatch
data:
  .kubewatch.yaml: |-
    handler:
      cloudevent:
        url: "http://{{ include "nudgebee-agent.fullname" . }}-runner:80/api/handle"
{{ toYaml .Values.kubewatch.config | indent 4 }}
