{{- if (and .Values.openshift.enabled .Values.openshift.createPrivilegedScc) }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ include "nudgebee-agent.fullname" . }}-scc-privileged
  labels:
    {{- include "nudgebee-agent.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: {{ include "nudgebee-agent.fullname" . }}-scc provides the features required to run robusta enhanced debuggers for Java, Python, and node host capabilities
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: true
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- SYS_PTRACE
- SYS_ADMIN
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
priority: {{ .Values.privilegedSccPriority }}
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users: []
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- secret
- hostPath
{{- end }}
