apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-playbooks-config-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  active_playbooks.yaml: |-
    {{ include "robusta.configfile" . | b64enc }}
