{{- if (and .Values.nodeAgent.enabled .Values.nodeAgent.podmonitor.enabled) }}
{{- if .Values.nodeAgent.podmonitor.azuremanaged }}
apiVersion: azmonitoring.coreos.com/v1
{{- else }}
apiVersion: monitoring.coreos.com/v1
{{- end }}
kind: PodMonitor
metadata:
  name: {{ include "nudgebee-agent.fullname" . }}-node-agent
  labels:
    {{- include "nudgebee-agent.labels" . | nindent 4 }}
    component: node-agent
spec:
  selector:
    matchLabels:
      {{- include "node-agent.selectorLabels" . | nindent 6 }}
      app: nudgebee-node-agent
  podMetricsEndpoints:
    - port: http
{{- end -}}