{{- if .Values.prometheusRule.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-rules
{{- if .Values.prometheusRule.namespace }}
  namespace: {{ .Values.prometheusRule.namespace }}
{{- else }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    app.kubernetes.io/component: nudgebee-agent
  {{- if .Values.prometheusRule.additionalLabels }}
    {{- toYaml .Values.prometheusRule.additionalLabels | nindent 4 }}
  {{- end }}
  {{- if .Values.prometheusRule.annotations }}
  annotations: {{ toYaml .Values.prometheusRule.annotations | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.prometheusRule.rules }}
  groups:
  - name: {{ .Release.Name }}-rules
    rules: {{- toYaml .Values.prometheusRule.rules | nindent 4 }}
{{- end }}
{{- end }}