{{- if (and (not .Values.runner.victoria_metrics_enabled) (.Values.alertmanager.create_nb_alert_config)) }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: {{ include "nudgebee-agent.fullname" . }}-alert-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nudgebee-agent.labels" . | nindent 4 }}
    component: alert-manager-config
spec:
  route:
    groupBy: []
    repeatInterval: 1h
    receiver: 'nudgebee-agent'
  receivers:
  - name: 'nudgebee-agent'
    matchers:
    - severity=~".*"
    webhookConfigs:
    - url: 'http://{{ include "nudgebee-agent.fullname" . }}-runner.{{ .Release.Namespace }}.svc/api/alerts'
      sendResolved: true
{{- end }}