name: Release RC Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-rc:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
  
      - name: Install AWS cli
        uses: unfor19/install-aws-cli-action@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Generate RC version
        id: rc_version
        run: |
          # Get current version from Chart.yaml
          CURRENT_VERSION=$(yq '.version' charts/nudgebee-agent/Chart.yaml)
          
          # Find existing RC releases for this version
          EXISTING_RCS=$(gh release list --json tagName --jq '.[] | select(.tagName | test("nudgebee-agent-'${CURRENT_VERSION}'-rc-[0-9]+$")) | .tagName' | sed 's/nudgebee-agent-'${CURRENT_VERSION}'-rc-//' | sort -n | tail -1)
          
          if [ -z "$EXISTING_RCS" ]; then
            RC_NUMBER=1
          else
            RC_NUMBER=$((EXISTING_RCS + 1))
          fi
          
          RC_VERSION="${CURRENT_VERSION}-rc-${RC_NUMBER}"
          echo "rc_version=$RC_VERSION" >> $GITHUB_OUTPUT
          echo "Generated RC version: $RC_VERSION"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Chart version for RC
        run: |
          cd charts/nudgebee-agent
          yq -i ".version=\"${{ steps.rc_version.outputs.rc_version }}\"" Chart.yaml
          yq -i ".appVersion=\"${{ steps.rc_version.outputs.rc_version }}\"" Chart.yaml
    
      - name: Update Helm Package for Nudgebee RC
        working-directory: ./charts/nudgebee-agent
        run: |
          nudgebee_app_image=`aws ecr describe-images --repository-name nudgebee-agent --filter tagStatus=TAGGED --query 'sort_by(imageDetails[?imageTags], &imagePushedAt)[-1].imageTags[0]' --region us-east-1 --output text`
          echo "nudgebee_app_image: $nudgebee_app_image"
          yq -i ".runner.image.tag=\"$nudgebee_app_image\"" values.yaml

          nudgebee_node_image=`aws ecr describe-images --repository-name nudgebee-node-agent --filter tagStatus=TAGGED  --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --region us-east-1 --output text --no-paginate`
          echo "nudgebee_node_image: $nudgebee_node_image"
          yq -i ".nodeAgent.image.tag=\"$nudgebee_node_image\"" values.yaml

          nudgebee_profile_image=`aws ecr describe-images --repository-name nudgebee-profiler-python --filter tagStatus=TAGGED --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --region us-east-1 --output text --no-paginate`
          echo "nudgebee_profile_image: $nudgebee_profile_image"
          yq -i ".runner.profiler_image_override=\"$nudgebee_profile_image\"" values.yaml

          nudgebee_krr_image=`aws ecr describe-images --repository-name krr-public --filter tagStatus=TAGGED --query 'sort_by(imageDetails[?imageTags != 'null'],& imagePushedAt)[-1].imageTags[0]' --region us-east-1 --output text --no-paginate`
          echo "nudgebee_krr_image: $nudgebee_krr_image"
          yq -i ".runner.krr_image_override=\"krr-public:$nudgebee_krr_image\"" values.yaml
          
          nudgebee_kubepug_image=`aws ecr describe-images --repository-name kubepug --filter tagStatus=TAGGED --query 'sort_by(imageDetails[?imageTags != 'null'],& imagePushedAt)[-1].imageTags[0]' --region us-east-1 --output text --no-paginate`
          echo "nudgebee_kubepug_image: $nudgebee_kubepug_image"
          yq -i ".runner.kubepug_image_override=\"kubepug:$nudgebee_kubepug_image\"" values.yaml
          
          nudgebee_nova_image=`aws ecr describe-images --repository-name nova --filter tagStatus=TAGGED --query 'sort_by(imageDetails[?imageTags != 'null'],& imagePushedAt)[-1].imageTags[0]' --region us-east-1 --output text --no-paginate`
          echo "nudgebee_nova_image: $nudgebee_nova_image"
          yq -i ".runner.nova_image_override=\"nova:$nudgebee_nova_image\"" values.yaml
          
          nudgebee_kubewatch_image=`aws ecr describe-images --repository-name kubewatch --filter tagStatus=TAGGED --query 'sort_by(imageDetails[?imageTags != 'null'],& imagePushedAt)[-1].imageTags[0]' --region us-east-1 --output text --no-paginate`
          echo "nudgebee_kubewatch_image: $nudgebee_kubewatch_image"
          yq -i ".kubewatch.image.tag=\"$nudgebee_kubewatch_image\"" values.yaml

          runbook_sidecar_image_tag=`aws ecr describe-images --repository-name nudgebee_runbook_sidecar_agent --filter tagStatus=TAGGED --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --region us-east-1 --output text --no-paginate`
          echo "runbook_sidecar_image_tag: $runbook_sidecar_image_tag"
          yq -i ".runner.runbook_sidecar_image_tag=\"$runbook_sidecar_image_tag\"" values.yaml
          
      - name: Add dependency chart repos
        run: |
          helm repo add opencost https://opencost.github.io/opencost-helm-chart

      - name: Run chart-releaser for RC
        uses: helm/chart-releaser-action@v1.4.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Create RC release notes
        run: |
          echo "## Release Candidate ${{ steps.rc_version.outputs.rc_version }}" > release_notes.md
          echo "" >> release_notes.md
          echo "This is a release candidate generated from the dev branch." >> release_notes.md
          echo "" >> release_notes.md
          echo "### Latest Images Used:" >> release_notes.md
          echo "- Built from latest dev branch commit: ${{ github.sha }}" >> release_notes.md
          echo "- Generated at: $(date)" >> release_notes.md
          echo "" >> release_notes.md
          echo "### Installation:" >> release_notes.md
          echo "\`\`\`bash" >> release_notes.md
          echo "helm repo add nudgebee https://nudgebee.github.io/k8s-agent" >> release_notes.md
          echo "helm repo update" >> release_notes.md
          echo "helm install nudgebee-agent nudgebee/nudgebee-agent --version ${{ steps.rc_version.outputs.rc_version }}" >> release_notes.md
          echo "\`\`\`" >> release_notes.md

      - name: Update GitHub release with RC notes
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "nudgebee-agent-${{ steps.rc_version.outputs.rc_version }}"
          name: "Release Candidate ${{ steps.rc_version.outputs.rc_version }}"
          body_path: release_notes.md
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}