name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
  
      - name: Update Helm Package for Nudgebee
        working-directory: ./deploy/kubernetes/nudgebee
        run: |
          nudgebee_app_image=`aws ecr describe-images --repository-name nudgebee-agent --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --region us-east-1 --output text --no-paginate`
          echo "nudgebee_app_image: $nudgebee_app_image"
          yq -i ".runner.image.tag=\"$nudgebee_app_image\"" values.yaml

      - name: Add dependency chart repos
        run: |
          helm repo add opencost https://opencost.github.io/opencost-helm-chart

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"