name: Update Image Tags on PR

on:
  pull_request:
    branches:
      - main
      - prod
    types: [opened, synchronize, reopened]

jobs:
  update-tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@master

      - name: Configure AWS Credentials for prod branch
        if: github.base_ref == 'prod'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Configure AWS Credentials for main branch
        if: github.base_ref == 'main'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update image tags
        working-directory: ./charts/nudgebee-agent
        run: |
          echo "Updating image tags for ${{ github.base_ref }} branch..."
          
          # Get latest images from ECR
          nudgebee_app_image=`aws ecr describe-images --repository-name nudgebee-agent --filter tagStatus=TAGGED --query 'sort_by(imageDetails[?imageTags], &imagePushedAt)[-1].imageTags[0]' --region us-east-1 --output text`
          echo "nudgebee_app_image: $nudgebee_app_image"
          yq -i ".runner.image.tag=\"$nudgebee_app_image\"" values.yaml

          nudgebee_node_image=`aws ecr describe-images --repository-name nudgebee-node-agent --filter tagStatus=TAGGED  --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --region us-east-1 --output text --no-paginate`
          echo "nudgebee_node_image: $nudgebee_node_image"
          yq -i ".nodeAgent.image.tag=\"$nudgebee_node_image\"" values.yaml

          nudgebee_profile_image=`aws ecr describe-images --repository-name nudgebee-profiler-python --filter tagStatus=TAGGED --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --region us-east-1 --output text --no-paginate`
          echo "nudgebee_profile_image: $nudgebee_profile_image"
          yq -i ".runner.profiler_image_override=\"$nudgebee_profile_image\"" values.yaml

          nudgebee_krr_image=`aws ecr describe-images --repository-name krr-public --filter tagStatus=TAGGED --query 'sort_by(imageDetails[?imageTags != 'null'],& imagePushedAt)[-1].imageTags[0]' --region us-east-1 --output text --no-paginate`
          echo "nudgebee_krr_image: $nudgebee_krr_image"
          yq -i ".runner.krr_image_override=\"krr-public:$nudgebee_krr_image\"" values.yaml
          
          nudgebee_kubepug_image=`aws ecr describe-images --repository-name kubepug --filter tagStatus=TAGGED --query 'sort_by(imageDetails[?imageTags != 'null'],& imagePushedAt)[-1].imageTags[0]' --region us-east-1 --output text --no-paginate`
          echo "nudgebee_kubepug_image: $nudgebee_kubepug_image"
          yq -i ".runner.kubepug_image_override=\"kubepug:$nudgebee_kubepug_image\"" values.yaml
          
          nudgebee_nova_image=`aws ecr describe-images --repository-name nova --filter tagStatus=TAGGED --query 'sort_by(imageDetails[?imageTags != 'null'],& imagePushedAt)[-1].imageTags[0]' --region us-east-1 --output text --no-paginate`
          echo "nudgebee_nova_image: $nudgebee_nova_image"
          yq -i ".runner.nova_image_override=\"nova:$nudgebee_nova_image\"" values.yaml
          
          nudgebee_kubewatch_image=`aws ecr describe-images --repository-name kubewatch --filter tagStatus=TAGGED --query 'sort_by(imageDetails[?imageTags != 'null'],& imagePushedAt)[-1].imageTags[0]' --region us-east-1 --output text --no-paginate`
          echo "nudgebee_kubewatch_image: $nudgebee_kubewatch_image"
          yq -i ".kubewatch.image.tag=\"$nudgebee_kubewatch_image\"" values.yaml

          runbook_sidecar_image_tag=`aws ecr describe-images --repository-name nudgebee_runbook_sidecar_agent --filter tagStatus=TAGGED --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --region us-east-1 --output text --no-paginate`
          echo "runbook_sidecar_image_tag: $runbook_sidecar_image_tag"
          yq -i ".runner.runbook_sidecar_image_tag=\"$runbook_sidecar_image_tag\"" values.yaml

      - name: Commit updated image tags
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          if [[ -n $(git status --porcelain) ]]; then
            git add charts/nudgebee-agent/values.yaml
            git commit -m "chore: update image tags for ${{ github.base_ref }} release

            Updated image tags to latest versions from ECR for ${{ github.base_ref }} branch.

            🤖 Generated with [Claude Code](https://claude.ai/code)

            Co-Authored-By: Claude <noreply@anthropic.com>"
            git push origin ${{ github.head_ref }}
            echo "Image tags updated and committed to PR branch"
          else
            echo "No changes to commit - image tags are already up to date"
          fi

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            
            const valuesChanged = files.some(file => file.filename.includes('values.yaml'));
            
            if (valuesChanged) {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `📦 **Image Tags Updated**
                
                I've automatically updated the image tags in \`charts/nudgebee-agent/values.yaml\` to the latest versions from ECR for the \`${{ github.base_ref }}\` branch.
                
                The image tags are now synchronized with the latest builds and ready for release.`
              });
            }